name: Condition

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
      python-version: '3.8'
    
    - name: Execute python
      run: python empty.py


  test:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
    - name: Display
      run: |
        echo "Le job n'est pas bon"