name: Condition

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs:  
      - build
    env:
      variable: ${{ env.SEUIL_CLASSIFICATION }}
    if: ${{ env.variable >= 0 && env.variable <= 1 }}
    steps:
    - name: Test
      run: echo "${{ env.variable }} est compris entre 0 et 1"
