name: Condition

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
      if: ${{ env.SEUIL_CLASSIFICATION >= 0 && env.SEUIL_CLASSIFICATION <= 1 }}
      run: echo "${{ env.SEUIL_CLASSIFICATION }} est compris entre 0 et 1"
    - uses: actions/checkout@v2