name: Condition

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    


  test:
    runs-on: ubuntu-latest
    needs: build
    - name: recup vars
      env:
        variable: ${{env.SEUIL_CLASSIFICATION}}
    if: $variable >= 0 && $variable <= 1
    steps:
    - name: Test
      run: echo "$variable est compris entre 0 et 1"