name: Condition

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
      python-version: '3.8'
    
    if: ${{ vars.seuil_classification >= 0 && vars.seuil_classification <= 1}}
    steps:
    - name: Test
      run: echo "$seuil_classification est compris entre 0 et 1"